global:
  scrape_interval: 120s
  scrape_timeout: 10s
  evaluation_interval: 120s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 120s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'api-log'
  scrape_interval: 120s
  metrics_path: /metrics
  static_configs:
    - targets: ['api:8080']
