services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_trad
    volumes:
      - ./bdd:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - my_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my_network

volumes:
  db_data:
  grafana_data:

networks:
  my_network: